version: '3.3'

services:
  streamlit:
    build: .
    container_name: crawler_streamlit_app
    ports:
      - "8505:8501"
    volumes:
      - .:/app
    restart: always
    depends_on:
      - redis
      - worker

  redis:
    container_name: crawler_streamlit_redis
    image: redis:7.0.5
    restart: always
    ports:
      - "6379:6379"

  worker:
    container_name: crawler_streamlit_worker
    build:
      context: .
      dockerfile: ./Dockerfile
    image: "crawler_streamlit_app"
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
    volumes:
      - .:/src
    command: ["sh", "scripts/celery_worker.sh"]
    depends_on:
      - redis

  scheduler:
    container_name: crawler_streamlit_scheduler
    build:
      context: .
      dockerfile: ./Dockerfile
    image: "crawler_streamlit_app"
    depends_on:
      - worker
      - redis
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
    volumes:
      - .:/src
    command: ["sh", "scripts/celery_beat.sh"]
